# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
      exclude: ^conda\.recipe/meta\.yaml$
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: trailing-whitespace

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9

  # Sort imports in a standard form
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort

  # Upgrade older Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]

  # Changes tabs to spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
    - id: remove-tabs

  # Flake8 code formatter
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    - id: flake8

  # Clang format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.3
    hooks:
    - id: clang-format
