[build-system]
requires = [
    "setuptools>=42",
    "cmake>=3.12",
    "ninja",
    "wheel",
    "pytest",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.cibuildwheel]
test-command = "pytest {project}/tests"
test-skip = "*universal2:arm64"
before-build = "rm -rf {project}/build"
