name: Build wheels

on:
  push:
    branches: [ "cpp" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macos-10.15 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up cmake
        uses: lukka/get-cmake@latest
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install MPI
        uses: mpi4py/setup-mpi@v1
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
