name: Build and test C++

on:
  push:
    branches: [ "cpp" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ windows-latest ]
        python-version: [ "3.9" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up cmake
        uses: lukka/get-cmake@latest
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python build dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install MPI
        uses: mpi4py/setup-mpi@v1
      - name: Prepare to compile C++
        run: |
          mkdir build
          cd build
          cmake -GNinja ..
      - name: Compile C++
        run: cmake --build build
      - name: Run tests
        run: ctest --test-dir build
