name: Build wheels

on:
  push:
    branches: [ "cpp" ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.9", "3.10" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up cmake
        uses: lukka/get-cmake@latest
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install MPI
        uses: mpi4py/setup-mpi@v1
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
