name: Build and test C++

on:
  push:
    branches: [ "cpp" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ] # windows-latest ]
        python-version: [ "3.9" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up cmake
        uses: lukka/get-cmake@latest
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python build dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install MPI
        uses: mpi4py/setup-mpi@v1
      - name: Install boost
        uses: MarkusJx/install-boost@v2.3.0
        id: install-boost
        with:
          boost_version: 1.78.0
      - name: Prepare to compile C++
        run: |
          mkdir build
          cd build
          cmake -GNinja .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBoost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include \
          -DBoost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - name: Compile C++
        run: cmake --build build
      - name: Run tests
        run: ./build/unit_tests
