name: Build and test C++

on:
  push:
    branches: [ "cpp" ]

jobs:
  windows-job:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: Set up cmake
        uses: lukka/get-cmake@latest
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python build dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install MPI
        uses: mpi4py/setup-mpi@v1
      - name: Prepare to compile C++
        run: |
          mkdir build
          cd build
          cmake -GNinja ..
        env:  # Set compilers to use MSVC (not MinGW)
          CC: cl
          CXX: cl
      - name: Compile C++
        run: cmake --build build --config Release
      - name: Run tests
        run: ctest --test-dir build

  linux-macos-jobs:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ "3.9" ]
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up cmake
        uses: lukka/get-cmake@latest
      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python build dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install MPI
        uses: mpi4py/setup-mpi@v1
      - name: Prepare to compile C++
        run: |
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
      - name: Compile C++
        run: cmake --build build
      - name: Run tests
        run: ctest --test-dir build
